require: rubocop-rspec

AllCops:
    NewCops: enable
Style/Documentation:
  Enabled: false
Layout/LineLength:
  Max: 100
MultipleExpectations:
  Enabled: false
MultipleMemoizedHelpers:
  Enabled: false